"""Render CONTENTS.md from the cache, and read watched state back out of it.

The file is regenerated wholesale every run. The only thing a human edits is
the checkboxes, and `read_watched` is what makes those survive: each entry
carries an invisible key anchor, so ticking a box still works after a folder
is renamed and the heading text changes.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional, Sequence

ANCHOR_RE = re.compile(r"<!--k:(?P<key>.+?)-->")
CHECKBOX_RE = re.compile(r"^\s*-\s*\[(?P<mark>[ xX])\]")

HEADER_NOTE = (
    "*Generated by [lazy-catalog](https://github.com/RafatH0ssain/lazy-catalog). "
    "Edit the checkboxes to mark things watched — everything else is overwritten "
    "on the next run.*"
)


def human_size(num_bytes: int) -> str:
    if num_bytes <= 0:
        return "0 B"
    units = ("B", "KB", "MB", "GB", "TB")
    size = float(num_bytes)
    for unit in units:
        if size < 1024 or unit == units[-1]:
            if unit in ("B", "KB"):
                return "{:.0f} {}".format(size, unit)
            return "{:.1f} {}".format(size, unit)
        size /= 1024
    return "{:.1f} TB".format(size)


def human_duration(minutes: Optional[int]) -> str:
    if not minutes:
        return ""
    hours, mins = divmod(int(minutes), 60)
    if hours and mins:
        return "{}h {}m".format(hours, mins)
    if hours:
        return "{}h".format(hours)
    return "{}m".format(mins)


def format_subs(subs: Sequence[str], limit: int = 3) -> str:
    """Name a few subtitle languages and count the rest.

    A streaming rip can carry thirty-five tracks, which is useful to know but
    unreadable to list. English is pulled to the front because that is the one
    the answer usually hinges on.
    """
    seen: List[str] = []
    for code in subs:
        code = (code or "").strip().lower()
        if code and code not in seen:
            seen.append(code)
    if len(seen) > 1 and "und" in seen:
        seen.remove("und")          # "undetermined" is noise beside real codes
    if not seen:
        return ""
    if "eng" in seen:
        seen.insert(0, seen.pop(seen.index("eng")))
    if len(seen) <= limit:
        return ", ".join(seen)
    return "{} +{}".format(", ".join(seen[:limit]), len(seen) - limit)


def _season_span(seasons: Dict[str, Any]) -> str:
    numbers = sorted(int(n) for n in seasons)
    if not numbers:
        return ""
    real = [n for n in numbers if n > 0]
    if not real:
        return "Specials only"
    if len(real) == 1:
        return "Season {}".format(real[0])
    if real == list(range(real[0], real[-1] + 1)):
        return "Seasons {}–{}".format(real[0], real[-1])
    return "Seasons " + ", ".join(str(n) for n in real)


def _tech_line(record: Dict[str, Any]) -> str:
    tech = record.get("tech") or {}
    bits: List[str] = []
    if tech.get("resolution"):
        bits.append(tech["resolution"])
    if tech.get("video"):
        bits.append(tech["video"])
    audio = tech.get("audio")
    if audio:
        channels = tech.get("channels")
        bits.append("{} {}".format(audio, channels).strip() if channels else audio)
    if tech.get("hdr"):
        bits.append(tech["hdr"])

    subs = format_subs(tech.get("subs") or [])
    if subs:
        bits.append("subs: " + subs)
    elif record.get("external_subs"):
        bits.append("subs: external")
    else:
        bits.append("no subs")

    if record.get("total_size"):
        bits.append(human_size(record["total_size"]))
    return " · ".join(b for b in bits if b)


def _facts_line(record: Dict[str, Any]) -> str:
    """Genres, runtime and rating — the parts that must be accurate."""
    mark = "" if record.get("enriched") else "~"
    bits: List[str] = []
    genres = record.get("genres") or []
    if genres:
        bits.append(mark + ", ".join(genres))

    if record.get("kind") == "series":
        span = _season_span(record.get("seasons") or {})
        if span:
            bits.append(span)
        if record.get("episode_count"):
            bits.append("{} episodes".format(record["episode_count"]))
        if record.get("specials"):
            bits.append("{} specials".format(record["specials"]))
    elif record.get("runtime"):
        bits.append(mark + human_duration(record["runtime"]))

    if record.get("rating"):
        bits.append("{}★ {:.1f}".format(mark, float(record["rating"])))
    return " · ".join(bits)


def _render_entry(record: Dict[str, Any]) -> List[str]:
    mark = "x" if record.get("watched") else " "
    title = record.get("title") or record["key"]
    year = record.get("year")
    heading = "**{}**".format(title)
    if year:
        heading += " ({})".format(year)

    facts = _facts_line(record)
    if facts:
        heading += " · " + facts

    lines = ["- [{}] {} <!--k:{}-->".format(mark, heading, record["key"])]

    overview = (record.get("overview") or "").strip()
    if overview:
        lines.append("      {}".format(overview))

    moods = record.get("moods") or []
    if moods:
        lines.append("      *{}*".format(" · ".join(moods)))

    tech = _tech_line(record)
    tail = "      `{}`".format(tech) if tech else ""
    if record.get("tmdb_url"):
        tail = (tail + " · " if tail else "      ") + "[TMDB]({})".format(record["tmdb_url"])
    if tail:
        lines.append(tail)

    lines.append("")
    return lines


def _stats(records: Sequence[Dict[str, Any]]) -> List[str]:
    films = [r for r in records if r.get("kind") == "film"]
    series = [r for r in records if r.get("kind") == "series"]
    total_size = sum(r.get("total_size") or 0 for r in records)

    minutes = 0
    for record in records:
        if record.get("kind") == "series":
            # No per-episode runtime from TMDB search, so approximate at the
            # series' episode runtime when known, else skip it entirely rather
            # than invent a number.
            runtime = record.get("runtime")
            if runtime:
                minutes += runtime * (record.get("episode_count") or 0)
        elif record.get("runtime"):
            minutes += record["runtime"]

    line = "{} titles · {} films · {} series · {}".format(
        len(records), len(films), len(series), human_size(total_size))
    if minutes:
        hours, mins = divmod(minutes, 60)
        line += " · {}h {}m of viewing".format(hours, mins)

    out = [line]

    counts: Dict[str, int] = {}
    for record in records:
        for genre in record.get("genres") or []:
            counts[genre] = counts.get(genre, 0) + 1
    if counts:
        ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
        out.append(" · ".join("{} {}".format(g, c) for g, c in ranked[:10]))

    watched = sum(1 for r in records if r.get("watched"))
    if watched:
        out.append("{} of {} watched".format(watched, len(records)))
    return out


def render(records: Iterable[Dict[str, Any]], now: Optional[datetime] = None) -> str:
    records = sorted(
        records, key=lambda r: (r.get("title") or r["key"]).lower())
    now = now or datetime.now()

    lines: List[str] = ["# TV Library", ""]
    lines.extend(_stats(records))
    lines.append("")
    lines.append(HEADER_NOTE)
    lines.append("")

    for kind, heading in (("film", "## Films"), ("series", "## Series")):
        group = [r for r in records if r.get("kind") == kind]
        if not group:
            continue
        lines.append(heading)
        lines.append("")
        for record in group:
            lines.extend(_render_entry(record))

    problems = [(r, r.get("issues") or []) for r in records]
    problems = [(r, i) for r, i in problems if i]
    if problems:
        lines.append("## Needs attention")
        lines.append("")
        for record, issues in problems:
            lines.append("- **{}** — {}".format(
                record.get("title") or record["key"], "; ".join(issues)))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Last updated {}*".format(now.strftime("%Y-%m-%d %H:%M")))
    lines.append("")
    return "\n".join(lines)


def read_watched(markdown: str) -> Dict[str, bool]:
    """Watched state keyed by folder name, from a previously rendered file."""
    state: Dict[str, bool] = {}
    for line in markdown.splitlines():
        box = CHECKBOX_RE.match(line)
        if not box:
            continue
        anchor = ANCHOR_RE.search(line)
        if not anchor:
            continue
        state[anchor.group("key")] = box.group("mark").lower() == "x"
    return state
